import type { EventRecord } from './types'
import type { CategorySlug } from './categories'

// ---------------------------------------------------------------------------
// Sample event data for Phase 1 UI. This is the ONLY place that knows where
// events come from. When Supabase is connected, replace the array + the
// synchronous getters below with async queries against the `events` table --
// the components consuming these helpers won't need to change shape.
// ---------------------------------------------------------------------------

const DAY = 24 * 60 * 60 * 1000
function iso(offsetDays: number): string {
  return new Date(Date.now() + offsetDays * DAY).toISOString().slice(0, 10)
}

export const PAST_EVENTS: EventRecord[] = [
  {
    id: 'evt-beit-midrash-elul-2026',
    title_he: "בית מדרש אֱלוּל",
    slug: "beit-midrash-elul-2026",
    short_description_he: "הצטרפו אלינו למסע לימוד והתבוננות לקראת חגי תשרי. דרך גמרא, חסידות ומקורות מהמסורת היהודית נתחבר לשאלות של התחדשות, סליחה, בחירה ומשמעות,…",
    full_description_he: "הצטרפו אלינו למסע לימוד והתבוננות לקראת חגי תשרי. דרך גמרא, חסידות ומקורות מהמסורת היהודית נתחבר לשאלות של התחדשות, סליחה, בחירה ומשמעות, ונכין את הלב לשנה החדשה. לימוד פתוח, נגיש ורלוונטי – ללא צורך בידע קודם.",
    hero_image: '/images/archive/archive-01-beit-midrash-elul.png',
    category: 'beit-midrash',
    start_date: '2026-08-17',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-levana-elul',
    title_he: "תֶּדֶר הַלְּבָנָה | אֱלוּל",
    slug: "teder-levana-elul",
    short_description_he: "תדר הלבנה הוא מרחב נשי של עצירה והתבוננות, שמתקיים בכל ראש חודש ומזמין אותנו להתחבר לזמן היהודי, למחזוריות של הטבע, ולמה שמבקש להיוולד…",
    full_description_he: "תדר הלבנה הוא מרחב נשי של עצירה והתבוננות, שמתקיים בכל ראש חודש ומזמין אותנו להתחבר לזמן היהודי, למחזוריות של הטבע, ולמה שמבקש להיוולד בתוכנו. בכל חודש אנחנו נפגשות למסע שמשלב מוזיקת תדרים אלקטרונית, טקסטים מהמסורת היהודית, מדיטציה, הקשבה וכתיבה.",
    hero_image: '/images/archive/archive-02-teder-levana-elul.png',
    category: 'workshops',
    start_date: '2026-08-13',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-levana-av',
    title_he: "תֶּדֶר הַלְּבָנָה | אָב",
    slug: "teder-levana-av",
    short_description_he: "מסע מוזיקלי־מדיטטיבי אל מהות החודש העברי. דרך מוזיקה, מדיטציה וחוכמת המסורת היהודית נתחבר לתדר הייחודי של החודש, לשערים שהוא פותח ולכוונות…",
    full_description_he: "מסע מוזיקלי־מדיטטיבי אל מהות החודש העברי. דרך מוזיקה, מדיטציה וחוכמת המסורת היהודית נתחבר לתדר הייחודי של החודש, לשערים שהוא פותח ולכוונות שהוא מזמין לחיינו. ערב של התחדשות, הקשבה פנימית ופתיחת הלב לקראת החודש החדש.",
    hero_image: '/images/archive/archive-03-teder-levana-av.png',
    category: 'workshops',
    start_date: '2026-07-14',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-levana-tamuz',
    title_he: "תֶּדֶר הַלְּבָנָה | תַּמּוּז",
    slug: "teder-levana-tamuz",
    short_description_he: "מסע מוזיקלי־מדיטטיבי אל מהות החודש העברי. דרך מוזיקה, מדיטציה וחוכמת המסורת היהודית נתחבר לתדר הייחודי של חודש תמוז, לשערים שהוא פותח…",
    full_description_he: "מסע מוזיקלי־מדיטטיבי אל מהות החודש העברי. דרך מוזיקה, מדיטציה וחוכמת המסורת היהודית נתחבר לתדר הייחודי של חודש תמוז, לשערים שהוא פותח ולכוונות שהוא מזמין לחיינו. ערב של התחדשות, הקשבה פנימית ופתיחת הלב לקראת החודש החדש.",
    hero_image: '/images/archive/archive-04-teder-levana-tamuz.png',
    category: 'workshops',
    start_date: '2026-06-22',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-shaarei-hapardes',
    title_he: "שַׁעֲרֵי הַפַּרְדֵּס — לימוד שבועי",
    slug: "shaarei-hapardes",
    short_description_he: "שערי כניסה לרוח היהודית דרך לימוד בית מדרשי של פרשת השבוע ועבודת הלב. מתכנסים כל שבוע, ביום רביעי.",
    full_description_he: "שערי כניסה לרוח היהודית דרך לימוד בית מדרשי של פרשת השבוע ועבודת הלב. מתכנסים כל שבוע, ביום רביעי.",
    hero_image: '/images/archive/archive-05-shaarei-hapardes.png',
    category: 'beit-midrash',
    start_date: '2026-06-10',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-shabbat-2026-03',
    title_he: "ארוחת שבת — ארמון בזמן",
    slug: "shabbat-2026-03",
    short_description_he: "מניין מזמינות אתכם להצטרף לארוחת שבת ארמון בזמן – חוויה מיוחדת המחברת בין מסורת, תרבות ורוחניות.",
    full_description_he: "מניין מזמינות אתכם להצטרף לארוחת שבת ארמון בזמן – חוויה מיוחדת המחברת בין מסורת, תרבות ורוחניות.",
    hero_image: '/images/archive/archive-06-shabbat-armon-bazman.webp',
    category: 'shabbat',
    start_date: '2026-03-20',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-mishte-purim',
    title_he: "מִשְׁתֵּה פּוּרִים",
    slug: "mishte-purim",
    short_description_he: "פותחים שער לכל הצבעים שבנו. קריאת מגילה עתיקה ומפתיעה, משתה פורים כיד המלך עם יין ואוכל בשפע, ומשם ישר למסיבה עם אפטר־סט אלקטרוני עם…",
    full_description_he: "פותחים שער לכל הצבעים שבנו. קריאת מגילה עתיקה ומפתיעה, משתה פורים כיד המלך עם יין ואוכל בשפע, ומשם ישר למסיבה עם אפטר־סט אלקטרוני עם סימפולים מתוך המגילה עדלאידע.",
    hero_image: '/images/archive/archive-07-purim.png',
    category: 'gatherings',
    start_date: '2026-03-02',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-shaarei-hasod',
    title_he: "שערי הסוד — תורת הקבלה כדרך חיים",
    slug: "shaarei-hasod",
    short_description_he: "מפגשי לימוד פתוחים לגילוי תורת הקבלה, בדרך המחוברת אלינו פה היום. המפגש פתוח בהרשמה מראש, בהנחיית רפאל כהן.",
    full_description_he: "מפגשי לימוד פתוחים לגילוי תורת הקבלה, בדרך המחוברת אלינו פה היום. המפגש פתוח בהרשמה מראש, בהנחיית רפאל כהן.",
    hero_image: '/images/archive/archive-08-shaarei-hasod.png',
    category: 'beit-midrash',
    start_date: '2026-01-14',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-ani-or-chanukah',
    title_he: "אני אור | במה פתוחה לחנוכה",
    slug: "ani-or-chanukah",
    short_description_he: "בנר הרביעי של חנוכה, ניפגש לערב שבו כל אחד ואחת מוזמנים לבטא את מה שחי בלב. במניין אנחנו מאמינים שלכולנו יש אור, לכולנו יש קול, ולכולנו יש…",
    full_description_he: "בנר הרביעי של חנוכה, ניפגש לערב שבו כל אחד ואחת מוזמנים לבטא את מה שחי בלב. במניין אנחנו מאמינים שלכולנו יש אור, לכולנו יש קול, ולכולנו יש מה להביא ללב של האחרים.",
    hero_image: '/images/archive/archive-09-ani-or-chanukah.png',
    category: 'gatherings',
    start_date: '2025-12-17',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-patuach-chanukah',
    title_he: "תדר פתוח חנוכה",
    slug: "teder-patuach-chanukah",
    short_description_he: "לימוד גמרא לקראת חג האור.",
    full_description_he: "לימוד גמרא לקראת חג האור.",
    hero_image: '/images/archive/archive-10-teder-patuach-chanukah.png',
    category: 'beit-midrash',
    start_date: '2025-12-13',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-erev-yom-kippur',
    title_he: "עֶרֶב יוֹם כִּפּוּר במניין",
    slug: "erev-yom-kippur",
    short_description_he: "בערב הקדוש ביותר בשנה, אנחנו עוצרים את השגרה ומתכנסים יחד ליצירת מרחב מיוחד להתכווננות.",
    full_description_he: "בערב הקדוש ביותר בשנה, אנחנו עוצרים את השגרה ומתכנסים יחד ליצירת מרחב מיוחד להתכווננות.",
    hero_image: '/images/archive/archive-11-erev-yom-kippur.jpg',
    category: 'gatherings',
    start_date: '2025-10-01',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-shaarei-neshima-2025',
    title_he: "שערי נשימה",
    slug: "shaarei-neshima-2025",
    short_description_he: "לקראת חודש הסליחות, אנחנו מזמינים אתכם לערב חד-פעמי של מסע נשימה מונחה, לימוד ומוסיקה חיה בפסנתר. חיבור מרפא של גוף, נפש ורוח. יחד נצלול…",
    full_description_he: "לקראת חודש הסליחות, אנחנו מזמינים אתכם לערב חד-פעמי של מסע נשימה מונחה, לימוד ומוסיקה חיה בפסנתר. חיבור מרפא של גוף, נפש ורוח. יחד נצלול פנימה, נקשיב לקול הפנימי, ונפתח שער אל לשוב אל עצמנו.",
    hero_image: '/images/archive/archive-12-shaarei-neshima.jpg',
    category: 'beit-midrash',
    start_date: '2025-09-17',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-patuach-elul',
    title_he: "תדר פתוח אלול",
    slug: "teder-patuach-elul",
    short_description_he: "הצטרפו אלינו לצלילה בדפי הגמרא שיכינו את הלב והנפש לחגי תשרי. לימוד גמרא נגיש, שמחבר בין מסורת עתיקה לרגעים האישיים של הזמן הזה. בואו לפתוח…",
    full_description_he: "הצטרפו אלינו לצלילה בדפי הגמרא שיכינו את הלב והנפש לחגי תשרי. לימוד גמרא נגיש, שמחבר בין מסורת עתיקה לרגעים האישיים של הזמן הזה. בואו לפתוח את השנה בתדר אחר — עם עומק, כוונה ולב פתוח. אין צורך בידע קודם.",
    hero_image: '/images/archive/archive-13-teder-patuach-elul.jpg',
    category: 'beit-midrash',
    start_date: '2025-09-02',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-armon-bazman-shabbat-2025',
    title_he: "ארמון בזמן | קבלת שבת",
    slug: "armon-bazman-shabbat-2025",
    short_description_he: "מניין ואל הלב מזמינים אתכם להצטרף לארמון בזמן – חוויה מיוחדת המחברת בין מסורת, תרבות ורוחניות.",
    full_description_he: "מניין ואל הלב מזמינים אתכם להצטרף לארמון בזמן – חוויה מיוחדת המחברת בין מסורת, תרבות ורוחניות.",
    hero_image: '/images/archive/archive-14-armon-bazman-shabbat.jpg',
    category: 'shabbat',
    start_date: '2025-08-29',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-erev-tisha-bav-2025',
    title_he: "ערב תשעה באב",
    slug: "erev-tisha-bav-2025",
    short_description_he: "הצטרפו אלינו למפגש מסוג אחר, מרחב שקט, פתוח ונושם. נתעמק יחד במגילת איכה מהזכרון ההיסטורי של חורבן לבית לשירה עתיקה של כאב וגעגוע.",
    full_description_he: "הצטרפו אלינו למפגש מסוג אחר, מרחב שקט, פתוח ונושם. נתעמק יחד במגילת איכה מהזכרון ההיסטורי של חורבן לבית לשירה עתיקה של כאב וגעגוע.",
    hero_image: '/images/archive/archive-15-erev-tisha-bav.png',
    category: 'gatherings',
    start_date: '2025-08-02',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-daf-yomi-b',
    title_he: "תֶּדֶר דְּיוֹמָא ב׳ — לימוד גמרא עם דופק חדשני",
    slug: "teder-daf-yomi-b",
    short_description_he: "מניין תל אביב מזמינים אתכם להצטרף למחזור ב׳ של תדר דיומא — לימוד גמרא חדשני ופורץ דרך המחבר בין מסורת, תודעה וחיים מודרניים. שישה מפגשים.",
    full_description_he: "מניין תל אביב מזמינים אתכם להצטרף למחזור ב׳ של תדר דיומא — לימוד גמרא חדשני ופורץ דרך המחבר בין מסורת, תודעה וחיים מודרניים. שישה מפגשים.",
    hero_image: '/images/archive/archive-16-teder-daf-yomi-b.jpg',
    category: 'beit-midrash',
    start_date: '2025-06-17',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-biur-chametz',
    title_he: "ביעור חמץ",
    slug: "biur-chametz",
    short_description_he: "הורידו טקס ביעור חמץ פנימי לפסח. שאלות לכתיבה, טקס שריפה ופתיחת כוונה חדשה. מבית מניין תל אביב. חג חירות שמח!",
    full_description_he: "הורידו טקס ביעור חמץ פנימי לפסח. שאלות לכתיבה, טקס שריפה ופתיחת כוונה חדשה. מבית מניין תל אביב. חג חירות שמח!",
    hero_image: '/images/archive/archive-17-biur-chametz.png',
    category: 'holidays',
    start_date: '2025-04-08',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-nisan',
    title_he: "מעגל ראש חודש ניסן",
    slug: "rosh-chodesh-nisan",
    short_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב…",
    full_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב של תפילה, שירה מקודשת, ולימוד לפתיחת שערי ראש חודש.",
    hero_image: '/images/archive/archive-18-rosh-chodesh-nisan.png',
    category: 'gatherings',
    start_date: '2025-03-29',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-adar',
    title_he: "ראש חודש אדר",
    slug: "rosh-chodesh-adar",
    short_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב…",
    full_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב של תפילה, שירה מקודשת, ולימוד לפתיחת שערי ראש חודש.",
    hero_image: '/images/archive/archive-19-rosh-chodesh-adar.png',
    category: 'gatherings',
    start_date: '2025-03-01',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-heichala-dechelma',
    title_he: "הֵיכְלָא דְּחֶלְמָא — מרחב לחלימה משותפת",
    slug: "heichala-dechelma",
    short_description_he: "מניין ומקדש רחם מזמינים אתכם להצטרף לליל חמישי בגלריית נווה שכטר, בו נצלול לעולם החלומות עם לימוד וסט האזנה מדיטטיבית עד לבוקר שישי. מגוון…",
    full_description_he: "מניין ומקדש רחם מזמינים אתכם להצטרף לליל חמישי בגלריית נווה שכטר, בו נצלול לעולם החלומות עם לימוד וסט האזנה מדיטטיבית עד לבוקר שישי. מגוון תאריכים לבחירה.",
    hero_image: '/images/archive/archive-20-heichala-dechelma.jpg',
    category: 'gatherings',
    start_date: '2025-02-20',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-teder-daf-yomi',
    title_he: "תֶּדֶר דְּיוֹמָא — לימוד עתיק עם דופק חדשני",
    slug: "teder-daf-yomi",
    short_description_he: "אנחנו מזמינים אתכם למסע של שישה מפגשים בהם נצלול יחד ללימוד הדף היומי, נתבונן כיצד הוא משקף את דופק החיים היהודי, ונחבר בין הטקסטים העתיקים…",
    full_description_he: "אנחנו מזמינים אתכם למסע של שישה מפגשים בהם נצלול יחד ללימוד הדף היומי, נתבונן כיצד הוא משקף את דופק החיים היהודי, ונחבר בין הטקסטים העתיקים של התלמוד לבין המסע האישי שלנו.",
    hero_image: '/images/archive/archive-21-teder-daf-yomi.jpg',
    category: 'beit-midrash',
    start_date: '2025-02-18',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-kalfei-or-chanukah',
    title_he: "קלפי אור לחנוכה",
    slug: "kalfei-or-chanukah",
    short_description_he: "קלפי האור – מסע של אור והשראה לחנוכה. ימי חנוכה הם הזדמנות לעצור, להתבונן באור הנרות, ולשאוב מהם השראה למסע האישי והמשפחתי שלנו. קלפי האור…",
    full_description_he: "קלפי האור – מסע של אור והשראה לחנוכה. ימי חנוכה הם הזדמנות לעצור, להתבונן באור הנרות, ולשאוב מהם השראה למסע האישי והמשפחתי שלנו. קלפי האור נוצרו במיוחד להעמקת החוויה של הדלקת הנרות, והם מוסיפים רובד רוחני ומשמעותי לכל אחד משמונת ימי החג.",
    hero_image: '/images/archive/archive-22-kalfei-or-chanukah.png',
    category: 'holidays',
    start_date: '2024-12-22',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-hachana-ruchanit-chanukah',
    title_he: "הכנה רוחנית לחנוכה",
    slug: "hachana-ruchanit-chanukah",
    short_description_he: "הצטרפו לערב הכנה מיוחד לחג החנוכה של מניין בשיתוף בית חנה הרבי. זהו הזמן שבו האור מתחיל לחזור ולהתגבר, סמל לתקווה חדשה ולהתחלה מחדש. בית…",
    full_description_he: "הצטרפו לערב הכנה מיוחד לחג החנוכה של מניין בשיתוף בית חנה הרבי. זהו הזמן שבו האור מתחיל לחזור ולהתגבר, סמל לתקווה חדשה ולהתחלה מחדש. בית מדרש, מדיטציה של מקדש רחם וסדנאות נוספות.",
    hero_image: '/images/archive/archive-23-hachana-ruchanit-chanukah.jpg',
    category: 'gatherings',
    start_date: '2024-12-21',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-kislev',
    title_he: "ראש חודש כסלו",
    slug: "rosh-chodesh-kislev",
    short_description_he: "הצטרפו אלינו לראש חודש כסלו — ערב של כוונה, התחדשות הלבנה ותפילה לעת הזו. ערב אינטימי בחלל מתוק בשוק הפשפשים ביפו.",
    full_description_he: "הצטרפו אלינו לראש חודש כסלו — ערב של כוונה, התחדשות הלבנה ותפילה לעת הזו. ערב אינטימי בחלל מתוק בשוק הפשפשים ביפו.",
    hero_image: '/images/archive/archive-24-rosh-chodesh-kislev.webp',
    category: 'gatherings',
    start_date: '2024-11-30',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-cheshvan',
    title_he: "ראש חודש חשון",
    slug: "rosh-chodesh-cheshvan",
    short_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב…",
    full_description_he: "מסורת יהודית עתיקה תופסת את ראש חודש כ\"זמן רצון\" — פרק זמן בו הקשר בין האדם לבוראו הוא יותר פתוח ורגיש לתפילות ולבקשות. הצטרפו אלינו לערב של תפילה, שירה מקודשת, ולימוד לפתיחת שערי ראש חודש.",
    hero_image: '/images/archive/archive-25-rosh-chodesh-cheshvan.webp',
    category: 'gatherings',
    start_date: '2024-11-02',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-shaarei-neshima-teshuva',
    title_he: "שערי נשימה — ערב של תשובה והתחדשות",
    slug: "shaarei-neshima-teshuva",
    short_description_he: "בימי התשובה שבין ראש השנה ליום הכיפורים ניפגש יחד לערב של עצירה, נשימה ושיבה פנימה אל עצמנו. הצטרפו אלינו ללימוד וסשן נשימות מעגלי —…",
    full_description_he: "בימי התשובה שבין ראש השנה ליום הכיפורים ניפגש יחד לערב של עצירה, נשימה ושיבה פנימה אל עצמנו. הצטרפו אלינו ללימוד וסשן נשימות מעגלי — ריברת'ינג.",
    hero_image: '/images/archive/archive-26-shaarei-neshima-teshuva.webp',
    category: 'beit-midrash',
    start_date: '2024-10-08',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-bein-hamerchavim',
    title_he: "בין המרחבים",
    slug: "bein-hamerchavim",
    short_description_he: "ביום בו מתחילים שלושת השבועות שבין צום שבעה עשר בתמוז לצום תשעה באב — אנחנו מתכנסים לקחת אוויר ולייצר בתוכנו יותר מרחב.",
    full_description_he: "ביום בו מתחילים שלושת השבועות שבין צום שבעה עשר בתמוז לצום תשעה באב — אנחנו מתכנסים לקחת אוויר ולייצר בתוכנו יותר מרחב.",
    hero_image: '/images/archive/archive-27-bein-hamerchavim.webp',
    category: 'gatherings',
    start_date: '2024-07-23',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-tamuz',
    title_he: "ראש חודש תמוז",
    slug: "rosh-chodesh-tamuz",
    short_description_he: "ערב של תפילות, כוונות ובקשות לעת הזו. הצטרפו לדניאלה דבש וליפז אלה לערב ראש חודש.",
    full_description_he: "ערב של תפילות, כוונות ובקשות לעת הזו. הצטרפו לדניאלה דבש וליפז אלה לערב ראש חודש.",
    hero_image: '/images/archive/archive-28-rosh-chodesh-tamuz.webp',
    category: 'gatherings',
    start_date: '2024-07-06',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-retreat-shavuot',
    title_he: "ריטריט להתעורר שבועות",
    slug: "retreat-shavuot",
    short_description_he: "ריטריט שנוצר מתוך רצון עמוק לחבר את חג השבועות לימים הלא פשוטים שאנחנו עוברים. בואו ליומיים של ניתוק בטבע המופלא של יבניאל, שבו נחווה תיקון…",
    full_description_he: "ריטריט שנוצר מתוך רצון עמוק לחבר את חג השבועות לימים הלא פשוטים שאנחנו עוברים. בואו ליומיים של ניתוק בטבע המופלא של יבניאל, שבו נחווה תיקון ליל שבועות עם לימוד תנועה וצלילים מרפאים.",
    hero_image: '/images/archive/archive-29-retreat-shavuot.webp',
    category: 'gatherings',
    start_date: '2024-06-11',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-sivan',
    title_he: "ראש חודש — סיוון",
    slug: "rosh-chodesh-sivan",
    short_description_he: "ראש חודש הוא זמן מיוחד שבו מתפתחת האפשרות להתחדשות ולשינוי. הצטרפו למניין ודניאלה דבש לערב מיוחד ביפו.",
    full_description_he: "ראש חודש הוא זמן מיוחד שבו מתפתחת האפשרות להתחדשות ולשינוי. הצטרפו למניין ודניאלה דבש לערב מיוחד ביפו.",
    hero_image: '/images/archive/archive-30-rosh-chodesh-sivan.webp',
    category: 'gatherings',
    start_date: '2024-06-06',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-rosh-chodesh-iyar',
    title_he: "ראש חודש — אייר",
    slug: "rosh-chodesh-iyar",
    short_description_he: "ליפז אלה ודניאלה דבש מזמינות אתכם למעגל ראש חודש בטמפל ביפו. ערב אינטימי שבו יתכנסו עד שני מניינים שירצו לצאת למסע יחד, של רוח, של לימוד…",
    full_description_he: "ליפז אלה ודניאלה דבש מזמינות אתכם למעגל ראש חודש בטמפל ביפו. ערב אינטימי שבו יתכנסו עד שני מניינים שירצו לצאת למסע יחד, של רוח, של לימוד ושל תפילה ושירה.",
    hero_image: '/images/archive/archive-31-rosh-chodesh-iyar.webp',
    category: 'gatherings',
    start_date: '2024-05-08',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
  {
    id: 'evt-maabedet-18',
    title_he: "מעבדת 18",
    slug: "maabedet-18",
    short_description_he: "בתקופה הזו שאנחנו נעים בין הלב השבור שלנו לבין הריפוי והחיים, מוזיקה ותפילה מאפשרים לנו מזור.",
    full_description_he: "בתקופה הזו שאנחנו נעים בין הלב השבור שלנו לבין הריפוי והחיים, מוזיקה ותפילה מאפשרים לנו מזור.",
    hero_image: '/images/archive/archive-32-maabedet-18.webp',
    category: 'gatherings',
    start_date: '2024-04-15',
    location_name: 'תל אביב',
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: false,
    status: 'completed',
  },
]

export const EVENTS: EventRecord[] = [
  {
    id: 'evt-shabbat-armon',
    title_he: 'ארוחת שבת — ארמון בזמן',
    slug: 'armon-bazman-shabbat',
    short_description_he:
      'ארוחת שבת חגיגית בלוקיישן מיוחד בלב תל אביב, עם אוכל יוצא דופן, יין וניגונים.',
    full_description_he:
      'מניין מזמינים אתכם לחוות ארוחת שבת מסוג חדש. אפשר להגיע עם חברים או לבד, להיפגש איתנו בלוקיישן לא שגרתי בלב העיר, לטעום אוכל יוצא דופן, לנוח מהשבוע שהיה ולהכיר אנשים חדשים על כוס יין. חוויה שמשלבת בין קודש וחול, בין מזרח ומערב, ובין עיר למסורת.',
    hero_image: '/images/shabbat.jpg',
    category: 'shabbat',
    tags: ['שבת', 'ארוחה', 'קהילה'],
    start_date: iso(6),
    doors_open: '19:00',
    start_time: '19:30',
    location_name: 'סטודיו במרכז תל אביב',
    address: 'רחוב לילינבלום 20, תל אביב',
    city: 'תל אביב',
    google_maps_url: 'https://maps.google.com/?q=Lilienblum+20+Tel+Aviv',
    capacity: 40,
    price: 120,
    registration_type: 'internal',
    internal_registration_enabled: true,
    facilitator: 'ליפז אלה',
    status: 'published',
    featured: true,
    show_remaining_capacity: true,
    confirmed_quantity: 28,
  },
  {
    id: 'evt-beit-midrash-elul',
    title_he: 'בית מדרש — יש לך כנפי רוח',
    slug: 'beit-midrash-kanfei-ruach',
    short_description_he:
      'ערב לימוד וחברותא סביב טקסטים, שירים וסיפורים ששופכים אור על החיים בעיר.',
    full_description_he:
      'עם הספר מחפש משמעות, ואנחנו במניין מבקשים להעמיק בטקסטים, שירים וסיפורים ששופכים אור ומאתגרים את המציאות של העיר הגדולה. בית המדרש של מניין הוא הזדמנות לקרוא, לחשוב, ולהסתכל במראה דרך האותיות — לגלות את עצמנו בתוך טקסט קאנוני בן אלפיים שנה ולהתרגש משיר בן עשור, באותה המידה בדיוק.',
    hero_image: '/images/beit-midrash.jpg',
    category: 'beit-midrash',
    tags: ['לימוד', 'חברותא'],
    start_date: iso(13),
    doors_open: '20:00',
    start_time: '20:15',
    location_name: 'בית קהילתי, פלורנטין',
    address: 'רחוב פלורנטין 10, תל אביב',
    city: 'תל אביב',
    google_maps_url: 'https://maps.google.com/?q=Florentin+10+Tel+Aviv',
    capacity: 30,
    price: 0,
    registration_type: 'internal',
    internal_registration_enabled: true,
    facilitator: 'ליפז אלה',
    status: 'published',
    featured: true,
    show_remaining_capacity: false,
    confirmed_quantity: 12,
  },
  {
    id: 'evt-havdalah-rooftop',
    title_he: 'הבדלה על הגג — התכנסות רוח',
    slug: 'havdalah-rooftop',
    short_description_he:
      'טקס הבדלה אינטימי על גג בתל אביב, עם ניגונים, בשמים ונר מבדיל בין קודש לחול.',
    full_description_he:
      'מעגל השנה היהודי שזור ברגעים מקודשים. סביב צאת השבת אנחנו מתכנסים על הגג לטקס הבדלה אחר — עם אלמנטים של מסורת לצד מודרנה, ניגונים, בשמים ונר מבדיל. הזדמנות לעצור, להיזכר, ולהביא את המסורת היהודית בחזרה אל המרחב היום-יומי שלנו.',
    hero_image: '/images/event-havdalah.png',
    category: 'gatherings',
    tags: ['הבדלה', 'רוח'],
    start_date: iso(20),
    doors_open: '20:30',
    start_time: '21:00',
    location_name: 'גג בעיר, מרכז תל אביב',
    address: 'שדרות רוטשילד 45, תל אביב',
    city: 'תל אביב',
    google_maps_url: 'https://maps.google.com/?q=Rothschild+45+Tel+Aviv',
    capacity: 25,
    price: 60,
    registration_type: 'internal',
    internal_registration_enabled: true,
    facilitator: 'ליפז אלה',
    status: 'published',
    featured: false,
    show_remaining_capacity: true,
    confirmed_quantity: 25, // sold out
  },
  ...PAST_EVENTS,
]

// --- Data access helpers (swap internals for Supabase later) ---------------

export function isPast(e: EventRecord): boolean {
  return e.status === 'completed' || new Date(e.start_date) < new Date(new Date().toDateString())
}

export function availableSpots(e: EventRecord): number | null {
  if (e.capacity == null) return null
  return Math.max(0, e.capacity - (e.confirmed_quantity ?? 0))
}

export function isSoldOut(e: EventRecord): boolean {
  if (e.status === 'sold_out') return true
  const spots = availableSpots(e)
  return spots !== null && spots <= 0
}

export function getPublishedUpcoming(): EventRecord[] {
  return EVENTS.filter((e) => e.status === 'published' && !isPast(e)).sort(
    (a, b) => +new Date(a.start_date) - +new Date(b.start_date),
  )
}

export function getPastEvents(): EventRecord[] {
  return EVENTS.filter((e) => isPast(e)).sort(
    (a, b) => +new Date(b.start_date) - +new Date(a.start_date),
  )
}

export function getFeatured(limit = 4): EventRecord[] {
  const upcoming = getPublishedUpcoming()
  const featured = upcoming.filter((e) => e.featured)
  return (featured.length ? featured : upcoming).slice(0, limit)
}

export function getByCategory(category: CategorySlug): EventRecord[] {
  return getPublishedUpcoming().filter((e) => e.category === category)
}

export function getEventBySlug(slug: string): EventRecord | undefined {
  return EVENTS.find((e) => e.slug === slug)
}

export function formatEventDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('he-IL', {
    day: 'numeric',
    month: 'long',
    weekday: 'long',
  })
}

export function formatEventDateShort(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('he-IL', {
    day: 'numeric',
    month: 'long',
  })
}
